# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StreamState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('c_key', models.CharField(max_length=100)),
                ('c_secret', models.CharField(max_length=100)),
                ('a_token', models.CharField(max_length=100)),
                ('a_secret', models.CharField(max_length=100)),
            ],
        ),
    ]
