# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_streamfilters_streamstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamfilters',
            name='languages',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='streamfilters',
            name='locations',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='streamstate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
