# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160804_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamfilters',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='streamfilters',
            name='locations',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
