# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160804_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamfilters',
            name='languages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='streamfilters',
            name='locations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
