# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_tweets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
